package com.adfmig.core.generate;

/**
 * The provenance header written at the top of every generated file.
 *
 * <p>Two things must be obvious to whoever opens the file a year from now: which ADF artifact it
 * came from, and that it is theirs to edit. The generated code is a starting point that the
 * customer owns outright — there is no runtime library of ours underneath it and no requirement to
 * keep this tool around. Saying so in the file itself is the point.
 */
public final class Generated {

    private Generated() {}

    public static String header(String sourceArtifact, String toolVersion) {
        return """
                /*
                 * Generated by adfmig %s from %s
                 *
                 * This file is yours to edit. It has no dependency on adfmig and none on the ADF
                 * runtime. Regenerating overwrites it, so once you start editing, stop regenerating.
                 *
                 * Search for TODO(adfmig: for anything the generator could not complete on its own.
                 */
                """.formatted(toolVersion, sourceArtifact);
    }
}
